title: Louis Deutsch's Blog
description: stats and mathy things
author: Louis Deutsch
theme: minima

header_pages:
  - index.md
  - blog.md
  - archive.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

collections:
  archive:
    output: true
    permalink: /archive/:name/

